### ISSUE TITLE
Apply your project to increase protein sequence diversity of a monomer

### ISSUE THREAD

**Issue by pdMM11** [luhong88/int_seq_des#2]
Congrats. It is a very nice paper and idea for that matter. 

I wonder if your GA code can be adapted to generate sequence diversity in a monomer. 

I have a test case protein on which there are two loop variable regions for which I want to generate novel sequences (and leave the rest of the protein sequence as in the wild-type). I have tried mutating with ProtenMPNN alone and with ESM alone (and other LLMs), but the sequence variability and/or AF2 predictions are not what I need.

**Comment by luhong88** [comment]
Hi @pdMM11 thanks for the comment.

I haven't thought much about loop design... but if you can come up with a set of objective functions that can characterize and define the loop properties you care about, then I do think this GA framework could be useful. I know in the "pre-ML" era, fragment sampling was a pretty promising way to do loop conformation prediction, so something like fragment quality score could be useful, e.g..

Have you tried some of the recent sequence space diffusion models such as EvoDiff? EvoDiff seems to work pretty well for disordered regions. Obviously not all loops have a highly dynamic structural ensemble, but I do wonder if such models will give you better sequences, either as standalone generative models or as a replacement for ProteinMPNN in the GA framework.

**Comment by pdMM11** [comment]
Thank you for the reply and for your insights. I'll try to come up with objective functions appropriate for sequence variability then. And thanks for the tip about EvoDiff. It looks very interesting for my case.

Best of luck.
